# Generated by Django 2.1.4 on 2018-12-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoKKT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_inn', models.CharField(max_length=32)),
                ('kkt_number', models.CharField(max_length=32)),
                ('fn_number', models.CharField(max_length=32)),
            ],
        ),
    ]
