# Generated by Django 2.1.4 on 2018-12-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_infokkt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KonturOfdApi',
        ),
    ]
