# Generated by Django 2.1.4 on 2019-01-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_konturofdapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoKKT',
        ),
    ]
