# Generated by Django 2.1.4 on 2018-12-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('under_group_name', models.CharField(max_length=64)),
                ('dish_name', models.CharField(max_length=64)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsToSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('goods_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_sync_bot.GoodsBase')),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.IntegerField(null=True)),
                ('receipt_num', models.IntegerField(null=True)),
                ('receipt_num_inshift', models.IntegerField(null=True)),
                ('deal_date', models.DateTimeField()),
                ('kkt_rnm', models.CharField(max_length=32)),
                ('fnnum', models.CharField(max_length=32)),
                ('address', models.CharField(choices=[('karla_libknehta', 'Карла Либкнехта'), ('vikulova', 'Викулова')], max_length=128)),
                ('receipt_type', models.CharField(choices=[('sale', 'Продажа'), ('open_shift', 'Открытие смены'), ('close_shift', 'Закрытие смены')], max_length=128)),
                ('is_fulled', models.BooleanField(default=False)),
                ('staff_name', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Наличный'), ('electronic', 'Безналичный')], max_length=64, null=True)),
                ('receipt_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sold_goods', models.ManyToManyField(blank=True, to='data_sync_bot.GoodsToSale')),
            ],
        ),
        migrations.DeleteModel(
            name='ReceiptData',
        ),
        migrations.DeleteModel(
            name='ShiftData',
        ),
    ]
