# Generated by Django 2.1.4 on 2018-12-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0002_auto_20181229_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePriceModificator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='PlacesToSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('quickresto_id', models.IntegerField(blank=True, null=True)),
                ('quickresto_place_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='goodsbase',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_sync_bot.PlacesToSell'),
        ),
        migrations.AddField(
            model_name='placepricemodificator',
            name='place_to_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_sync_bot.PlacesToSell'),
        ),
        migrations.AddField(
            model_name='goodsbase',
            name='base_price',
            field=models.ManyToManyField(to='data_sync_bot.PlacePriceModificator'),
        ),
    ]
