# Generated by Django 2.1.4 on 2018-12-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0003_auto_20181229_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placestosell',
            name='quickresto_place_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
