# Generated by Django 2.1.4 on 2018-12-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0004_auto_20181229_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpoyeesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(blank=True, max_length=64, null=True)),
                ('rate_per_hour', models.IntegerField(default=100, null=True)),
                ('quickresto_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_sync_bot.EmpoyeesList'),
        ),
    ]
