# Generated by Django 2.1.4 on 2019-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0006_goodsbase_quickresto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsbase',
            name='base_price',
            field=models.ManyToManyField(blank=True, to='data_sync_bot.PlacePriceModificator'),
        ),
    ]
