# Generated by Django 2.1.4 on 2019-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0007_auto_20190109_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsbase',
            name='quickresto_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
