# Generated by Django 2.1.4 on 2019-01-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0008_auto_20190109_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsbase',
            name='keyword_ident',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
