# Generated by Django 2.1.4 on 2019-01-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0011_remove_placestosell_keyword_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='placestosell',
            name='fn_number',
            field=models.CharField(default=12345, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placestosell',
            name='ip_inn',
            field=models.CharField(default=12345, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placestosell',
            name='kkt_number',
            field=models.CharField(default=12345, max_length=32),
            preserve_default=False,
        ),
    ]
