# Generated by Django 2.1.4 on 2019-01-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0012_auto_20190111_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='empoyeeslist',
            name='mask_ident',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
