# Generated by Django 2.1.4 on 2019-01-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0013_empoyeeslist_mask_ident'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpoyeesList',
            new_name='EmployeesList',
        ),
    ]
