# Generated by Django 2.1.4 on 2019-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0014_auto_20190113_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placestosell',
            name='quickresto_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
