# Generated by Django 2.1.4 on 2019-01-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0016_salesdata_is_uploaded_quickresto'),
    ]

    operations = [
        migrations.AddField(
            model_name='placestosell',
            name='quickresto_kkm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
