# Generated by Django 2.1.4 on 2019-01-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0017_placestosell_quickresto_kkm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placestosell',
            name='quickresto_id',
        ),
        migrations.RemoveField(
            model_name='placestosell',
            name='quickresto_place_name',
        ),
        migrations.AddField(
            model_name='placestosell',
            name='quickresto_cookplace_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='placestosell',
            name='quickresto_place_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='quickresto_shift_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeslist',
            name='quickresto_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='placestosell',
            name='quickresto_kkm_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
