# Generated by Django 2.1.4 on 2019-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync_bot', '0018_auto_20190119_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='quickresto_receipt_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
